# Generated by Django 5.0 on 2024-06-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apihandle", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="away_team_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="fixture_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="home_team_id",
            field=models.IntegerField(default=0),
        ),
    ]
