# Generated by Django 5.0 on 2024-06-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apihandle", "0004_delete_stream_remove_match_live_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="liveurl",
            field=models.URLField(blank=True, null=True),
        ),
    ]
