# Generated by Django 5.0 on 2024-06-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apihandle", "0006_remove_match_venue_city_remove_match_venue_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilterCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
